1st assignment
Nahid1911/MV_repository_1st_Project pull request #1
Opened 2023-03-22 16:41 UTC by Nahid1911

HTML, CSS, .gitignore file added 
requesting your comments

2023-03-22 20:19 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi @Nahid1911 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 
- No linter errors :+1: 
- Good use of GitHub flow :+1: 
- Good use of gitignore :+1: 
## Required Changes ♻️
- [ ] Good job using the right README template, However, you have forgotten to customize each section with your data and remove or replace the Microverse logo, kindly customize it considering the fact that the FAQ section is the only optional part of it :recycle: 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 05:53 UTC, shella12 requested changes
Hi  @Nahid1911 , 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- All linters passed ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] [OPTIONAL] Please use descriptive commit messages. The commit message should be written in the imperative tense and capitalized.  For example insted of saying "
ammended readme.md file with personal and project information, remove…" say "UPDATE README.md" [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8). Its one of the requirements of the project but please try to keep this in mind for future

<img width="880" alt="Screenshot 2023-03-23 at 10 45 27 AM" src="https://user-images.githubusercontent.com/44798044/227115493-9a5eb9b9-9994-4c4f-b2b6-a6e0120147cc.png">


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 05:53 UTC, shella12 commented on README.md
> +  <img src=" " alt="logo" width="140"  height="auto" />
- [ ] Great job 👍 using [Microverse template](https://github.com/microverseinc/readme-template) for your README.md however as requested by the previous reviewer please 🙏  make sure to customise this template by adding descriptions to each section, reflecting your project. Also make sure to take care of the following:

       - Please remove Note from the LICENCE section of the README. Note is there in the template to guide you on how you to add a LICENCE to your README. Once you have successfully added the LICENCE you can go ahead and remove it
       - The link to your `MIT LICENCE` is broken. Please use these [guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to correctly add LICENCE into your README.
       - Please remove the Microverse logo from your readme. Optionally, you can replace with your own logo if you want.
       - Please remove the default comment like
       
            > Give credit to everyone who inspired your codebase.  
           > Write a message to encourage readers to support your project  
           > Describe 1 - 3 features you will add to the project.  
          
          ,etc from your README. 
          They were used in the template to explain to the user the purpose of each section. You can go ahead and remove it from your README

2023-03-23 07:01 UTC, shella12 requested changes
Hi @Nahid1911 , 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- All linters passed ✅ 

 ## Required Changes ♻️

- [ ] Great job adding the` MIT Licence` file into your repo however when you click the `MIT link` on your` README` it takes to `ERROR 404 not found`  page the reason for this is because your link to the licence is broken. The correct way of linking the files in your repo is use their directory path here the file is in your root so you can simply link it like this `[MIT](./LICENCE.md)` if your licence is named MIT.md  link it like this `[MIT](./MIT.md)`

<img width="339" alt="Screenshot 2023-03-23 at 11 49 09 AM" src="https://user-images.githubusercontent.com/44798044/227125903-73c63a6c-dcf2-4c46-ab3a-84d328519db9.png">

- [ ] Please include `Future Feature` section in your README, as suggested previously please make sure all the main sections from template have been added to your README. Kindly 🙏 refer to this [template link](https://github.com/microverseinc/readme-template) to ensure all section have been added along with their description to reflect your project. 

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 07:01 UTC, shella12 commented on LICENSE.md
- [ ] Your licence file is empty however there is another LICENCE file `MIT.md` in your Repo that consists of the license I would suggest deleting this one and using that in your LICENCE link

2023-03-23 08:00 UTC, braincee requested changes
Hello @Nahid1911 ✋, I am @braincee your Code Reviewer

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


![so-close](https://user-images.githubusercontent.com/78104544/225492039-ed22bba9-481a-489f-ae04-74623970af20.gif)

HIGHLIGHTS
------

 - GitHub flow rightfully used ✅
 - Meaningful title and summary for PR ✅
 - Professional README.md file ✅
 - No linter errors ✅

REQUIRED CHANGES ♻️
------

- [ ] Please add a setup section to the README file so that developers can clone the repository. 😃 
Example: 
`cd my-folder`
`https://github.com/Nahid1911/MV_repository_1st_Project.git`


**_Please check the comments under the review._**

OPTIONAL CHANGES
--------
**_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._**

- [ ] [OPTIONAL] I kindly suggest you add an installation section to the README file. This is an HTML and CSS project so the installation process will be `npm install / npm i`. 
- [ ] [OPTIONAL] I kindly suggest you add prerequisites to the README file so the project looks professional. 
Example:

- Have some knowledge of HTML and CSS
- Be familiar with git commands
- Basics understanding of Linters

- [ ] [OPTIONAL] I kindly suggest adding a run test section to the README file so it looks professional. Example: `npx hint .`, `npx stylelint "**/*.{css,scss}"`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @braincee in your question so I can receive the notification.

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

----

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 08:00 UTC, braincee commented on README.md
>  - [Live Demo Link](https://google.com)
- [ ] [OPTIONAL] I kindly suggest you remove demo live link since this project has not been deployed yet

2023-03-23 08:00 UTC, braincee commented on README.md
>  <!-- PROJECT DESCRIPTION -->
- [ ] [OPTIONAL] I kindly suggest you add a short description to about the project

2023-03-23 08:46 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi  @Nahid1911  👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉

## Highlights
✔ Used correct GitFlow👍 
✔ No Linter Errors 👍 
✔ Made the required changes👍 

## Optional Requirement

- [ ] Check the comments below 👇 

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 08:46 UTC, TuyishimireEric commented on README.md
- [ ] **[Optional] Good job on using the microverse Readme template 👍** However,

    I think it would be better to provide a  valid **LICENSE** link in your **README** as open source software needs to be licensed to provide rights to **modify**, **distribute** other than creator :joy: 

    _we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). You can also use [any other license](https://choosealicense.com/licenses/) if you wish._

2023-03-23 08:58 UTC, merged